if (NOT DEFINED CMAKE_INSTALL_PREFIX)
    message(STATUS "CMAKE_INSTALL_PREFIX not defined, install options not available")
    return()
endif()

message(STATUS "CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}")

cmake_path(APPEND CMAKE_INSTALL_LIBDIR ${CMAKE_INSTALL_PREFIX} "lib")
message(STATUS "CMAKE_INSTALL_LIBDIR: ${CMAKE_INSTALL_LIBDIR}")

cmake_path(APPEND CMAKE_INSTALL_INCLUDEDIR ${CMAKE_INSTALL_PREFIX} "include")
message(STATUS "CMAKE_INSTALL_INCLUDEDIR: ${CMAKE_INSTALL_INCLUDEDIR}")

install(
    FILES ${CMAKE_SOURCE_DIR}/include/OpenID.hpp
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
install(
    TARGETS OpenID
    DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

if (C_INTERFACE)
install(
    FILES ${CMAKE_SOURCE_DIR}/include/OpenID.h
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
install(
    TARGETS OpenIDC
    DESTINATION ${CMAKE_INSTALL_LIBDIR}
)
endif()
